steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'backend'

  # Build and deploy directly to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'cvpro-backend',
        '--source',
        'backend',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

# Cloud Build needs permission to deploy to Cloud Run
options:
  logging: CLOUD_LOGGING_ONLY
